[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200

board_build.pio = src/ws2812.pio

build_flags =
    -I lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/ff15/source
    -I lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/include
    -I lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/sd_driver
    -D ARM_MATH_CM33
    -D __FPU_PRESENT=1
    -D __DSP_PRESENT=1

build_src_filter =
    +<*>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/ff15/source/ff.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/ff15/source/ffunicode.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/ff15/source/ffsystem.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/sd_driver/*.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/src/f_util.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/src/ff_stdio.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/src/glue.c>
    +<../lib/no-OS-FatFS-SD-SPI-RPi-Pico/FatFs_SPI/src/my_debug.c>